services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_tts_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - GOOGLE_APPLICATION_CREDENTIALS=/backend/credentials/google-credentials.json
    volumes:
      - .:/backend
      - ./credentials:/backend/credentials:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend_network
    restart: unless-stopped

networks:
  backend_network:
    driver: bridge
